function renderDramaCards(sectionId, dramas, title) {
      const container = document.getElementById(sectionId);
        if (!container) return;

          container.innerHTML = `
              <div class="flex items-end justify-between mb-8">
                    <h2 class="text-4xl font-bold flex items-center gap-4">${title}</h2>
                        </div>
                            <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 2xl:grid-cols-7 gap-6" id="${sectionId}-grid"></div>
                              `;

                                const grid = document.getElementById(`${sectionId}-grid`);

                                  dramas.forEach(drama => {
                                      const card = document.createElement('div');
                                          card.className = `drama-card cursor-pointer bg-zinc-900 rounded-3xl overflow-hidden`;
                                              card.innerHTML = `
                                                    <div class="relative">
                                                            <img src="\( {drama.image}" class="w-full aspect-[2/3] object-cover" alt=" \){drama.title}">
                                                                    <div class="absolute top-3 left-3 bg-black/70 text-xs px-3 py-1 rounded-full">${drama.category ? drama.category.split(',')[0] : 'Drama'}</div>
                                                                          </div>
                                                                                <div class="p-5">
                                                                                        <h3 class="font-semibold text-lg leading-tight line-clamp-2 mb-2">${drama.title}</h3>
                                                                                                <p class="text-zinc-500 text-sm">${drama.hits || 0} views</p>
                                                                                                      </div>
                                                                                                          `;
                                                                                                              card.addEventListener('click', () => showDramaDetail(drama.id));
                                                                                                                  grid.appendChild(card);
                                                                                                                    });
                                                                                                                    }

                                                                                                                    async function showDramaDetail(id) {
                                                                                                                      const data = await getDramaInfo(id);
                                                                                                                        if (data.status !== 1) return alert("Gagal memuat detail drama");

                                                                                                                          let html = `
                                                                                                                              <div class="fixed inset-0 bg-black/95 z-[100] flex items-center justify-center p-4 overflow-y-auto" id="detail-modal">
                                                                                                                                    <div class="modal bg-zinc-900 max-w-5xl w-full rounded-3xl overflow-hidden relative">
                                                                                                                                            <button onclick="closeModal()" class="absolute top-6 right-6 text-4xl hover:text-rose-500 z-10">✕</button>
                                                                                                                                                    
                                                                                                                                                            <div class="flex flex-col lg:flex-row">
                                                                                                                                                                      <div class="lg:w-96 flex-shrink-0">
                                                                                                                                                                                  <img src="\( {data.image}" class="w-full h-full object-cover" alt=" \){data.title}">
                                                                                                                                                                                            </div>
                                                                                                                                                                                                      <div class="flex-1 p-8 lg:p-10">
                                                                                                                                                                                                                  <h1 class="text-5xl font-bold mb-4">${data.title}</h1>
                                                                                                                                                                                                                              <div class="flex flex-wrap gap-x-6 gap-y-2 text-sm text-zinc-400 mb-8">
                                                                                                                                                                                                                                            <span>${data.category || 'Drama'}</span>
                                                                                                                                                                                                                                                          <span>${data.total_episode || '?'} Episode</span>
                                                                                                                                                                                                                                                                        <span>${data.hits || 0} views</span>
                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                <p class="text-zinc-300 leading-relaxed mb-10">${data.synopsis_clean || data.synopsis || "Sinopsis tidak tersedia."}</p>
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                        <h3 class="text-2xl font-semibold mb-6">Daftar Episode</h3>
                                                                                                                                                                                                                                                                                                                                    <div class="grid grid-cols-2 md:grid-cols-3 gap-4 max-h-96 overflow-y-auto pr-2" id="episode-list"></div>
                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                  `;

                                                                                                                                                                                                                                                                                                                                                                    document.getElementById('modal-container').innerHTML = html;

                                                                                                                                                                                                                                                                                                                                                                      const epContainer = document.getElementById('episode-list');
                                                                                                                                                                                                                                                                                                                                                                        if (data.data_episode && data.data_episode.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                            data.data_episode.forEach(ep => {
                                                                                                                                                                                                                                                                                                                                                                                  const div = document.createElement('div');
                                                                                                                                                                                                                                                                                                                                                                                        div.className = "bg-zinc-800 hover:bg-zinc-700 rounded-2xl overflow-hidden cursor-pointer transition-all";
                                                                                                                                                                                                                                                                                                                                                                                              div.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                      <img src="${ep.episode_image || data.image}" class="w-full aspect-video object-cover">
                                                                                                                                                                                                                                                                                                                                                                                                              <div class="p-4 text-sm">${ep.episode_label || 'Episode ' + (ep.episode || '')}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                    `;
                                                                                                                                                                                                                                                                                                                                                                                                                          div.addEventListener('click', () => playEpisode(ep.episode_id || ep.id));
                                                                                                                                                                                                                                                                                                                                                                                                                                epContainer.appendChild(div);
                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                      async function playEpisode(episodeId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!episodeId) return alert("Streaming belum tersedia");
                                                                                                                                                                                                                                                                                                                                                                                                                                          const stream = await getStreamLink(episodeId);
                                                                                                                                                                                                                                                                                                                                                                                                                                            const link = stream['720p'] || stream['480p'];
                                                                                                                                                                                                                                                                                                                                                                                                                                              if (link) window.open(link, '_blank');
                                                                                                                                                                                                                                                                                                                                                                                                                                                else alert("Link streaming tidak ditemukan");
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                function closeModal() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  const modal = document.getElementById('detail-modal');
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (modal) modal.remove();
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
}